name: nlp_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=1.26
  - scipy=1.11
  - pandas=2.2
  - scikit-learn=1.5
  - gensim=4.3
  - matplotlib
  - seaborn
  - nltk
  - jupyterlab
  - notebook
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.17.1
      - torchaudio==2.6.0
      - tensorflow==2.16.1
      - tf-keras~=2.16
      - transformers==4.39.2
      - datasets==2.15.1
      - sentence-transformers==5.1.0
      - sentencepiece==0.1.99
      - safetensors==0.3.2
      - tqdm==4.66.1
      - pillow==10.1.0
      - typing_extensions==4.9.0
